name: paje_db
dependencies:
    - python=3.7
    - numpy=1.16.*
    - scikit-learn=0.22.*
    - imbalanced-learn
    - pandas
    - matplotlib
    - mysql-connector-python
    - lz4
    - zstd
    - blosc
    - imbalanced-learn
    - pip:
        - openml
        - pymfe
        - zstd
